{
 "title": "Snort Dashboard",
 "description": "Snort Dashboard",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensor_name",
    "label": "sensor_location",
    "query": "{\"find\":\"terms\",\"field\":\"sensor_name.keyword\"}"
   }
  ]
 },
 "panels": [
  { "title": "Event Severity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "High Severity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "severity.keyword:High AND $sensor_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Medium Severity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "severity.keyword:Medium AND $sensor_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Low Severity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "severity.keyword:Low AND $sensor_name",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Current Time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 } },
  { "title": "Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Event by sensor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Events" }
   ],
   "targets": [
    {
     "alias": "{{sensor_name.keyword}} severity {{severity.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "severity.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "sensor_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "3", "type": "count" }
     ],
     "query": "$sensor_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Alert Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 5 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "alert_description.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "alert_description",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "$sensor_name",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Destination IPs",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "DstGeoip.ip",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "DstGeoip.location",
       "id": "3",
       "settings": { "precision": 3 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      {
       "field": "ip",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Source IPs",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "SrcGeoip.ip",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "SrcGeoip.location",
       "id": "3",
       "settings": { "precision": 3 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      {
       "field": "ip",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Alert_description",
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "$sensor_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Source IP",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "SrcIp",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "$sensor_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Destination Port",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "DstPort",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "$sensor_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Destination IP",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "DstIp",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "$sensor_name",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Protocole vs Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Events" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "protocol.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "$sensor_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Classifications",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 40 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "classification.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "$sensor_name",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}